/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as SkillTestIndexRouteImport } from './routes/skill-test/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as MockTestIndexRouteImport } from './routes/mock-test/index'
import { Route as SkillTestSlugRouteImport } from './routes/skill-test/$slug'
import { Route as StudyThemeSlugIndexRouteImport } from './routes/study/$themeSlug/index'
import { Route as MockTestAttemptIdIndexRouteImport } from './routes/mock-test/$attemptId/index'
import { Route as MockTestAttemptIdResultRouteImport } from './routes/mock-test/$attemptId/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillTestIndexRoute = SkillTestIndexRouteImport.update({
  id: '/skill-test/',
  path: '/skill-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestIndexRoute = MockTestIndexRouteImport.update({
  id: '/mock-test/',
  path: '/mock-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillTestSlugRoute = SkillTestSlugRouteImport.update({
  id: '/skill-test/$slug',
  path: '/skill-test/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyThemeSlugIndexRoute = StudyThemeSlugIndexRouteImport.update({
  id: '/study/$themeSlug/',
  path: '/study/$themeSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestAttemptIdIndexRoute = MockTestAttemptIdIndexRouteImport.update({
  id: '/mock-test/$attemptId/',
  path: '/mock-test/$attemptId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestAttemptIdResultRoute = MockTestAttemptIdResultRouteImport.update({
  id: '/mock-test/$attemptId/result',
  path: '/mock-test/$attemptId/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skill-test/$slug': typeof SkillTestSlugRoute
  '/mock-test/': typeof MockTestIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skill-test/': typeof SkillTestIndexRoute
  '/study/': typeof StudyIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/mock-test/$attemptId/result': typeof MockTestAttemptIdResultRoute
  '/mock-test/$attemptId/': typeof MockTestAttemptIdIndexRoute
  '/study/$themeSlug/': typeof StudyThemeSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skill-test/$slug': typeof SkillTestSlugRoute
  '/mock-test': typeof MockTestIndexRoute
  '/plan': typeof PlanIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/skill-test': typeof SkillTestIndexRoute
  '/study': typeof StudyIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/mock-test/$attemptId/result': typeof MockTestAttemptIdResultRoute
  '/mock-test/$attemptId': typeof MockTestAttemptIdIndexRoute
  '/study/$themeSlug': typeof StudyThemeSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skill-test/$slug': typeof SkillTestSlugRoute
  '/mock-test/': typeof MockTestIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skill-test/': typeof SkillTestIndexRoute
  '/study/': typeof StudyIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/mock-test/$attemptId/result': typeof MockTestAttemptIdResultRoute
  '/mock-test/$attemptId/': typeof MockTestAttemptIdIndexRoute
  '/study/$themeSlug/': typeof StudyThemeSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skill-test/$slug'
    | '/mock-test/'
    | '/plan/'
    | '/settings/'
    | '/skill-test/'
    | '/study/'
    | '/teacher/'
    | '/mock-test/$attemptId/result'
    | '/mock-test/$attemptId/'
    | '/study/$themeSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/skill-test/$slug'
    | '/mock-test'
    | '/plan'
    | '/settings'
    | '/skill-test'
    | '/study'
    | '/teacher'
    | '/mock-test/$attemptId/result'
    | '/mock-test/$attemptId'
    | '/study/$themeSlug'
  id:
    | '__root__'
    | '/'
    | '/skill-test/$slug'
    | '/mock-test/'
    | '/plan/'
    | '/settings/'
    | '/skill-test/'
    | '/study/'
    | '/teacher/'
    | '/mock-test/$attemptId/result'
    | '/mock-test/$attemptId/'
    | '/study/$themeSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillTestSlugRoute: typeof SkillTestSlugRoute
  MockTestIndexRoute: typeof MockTestIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SkillTestIndexRoute: typeof SkillTestIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  MockTestAttemptIdResultRoute: typeof MockTestAttemptIdResultRoute
  MockTestAttemptIdIndexRoute: typeof MockTestAttemptIdIndexRoute
  StudyThemeSlugIndexRoute: typeof StudyThemeSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-test/': {
      id: '/skill-test/'
      path: '/skill-test'
      fullPath: '/skill-test/'
      preLoaderRoute: typeof SkillTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test/': {
      id: '/mock-test/'
      path: '/mock-test'
      fullPath: '/mock-test/'
      preLoaderRoute: typeof MockTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-test/$slug': {
      id: '/skill-test/$slug'
      path: '/skill-test/$slug'
      fullPath: '/skill-test/$slug'
      preLoaderRoute: typeof SkillTestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$themeSlug/': {
      id: '/study/$themeSlug/'
      path: '/study/$themeSlug'
      fullPath: '/study/$themeSlug/'
      preLoaderRoute: typeof StudyThemeSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test/$attemptId/': {
      id: '/mock-test/$attemptId/'
      path: '/mock-test/$attemptId'
      fullPath: '/mock-test/$attemptId/'
      preLoaderRoute: typeof MockTestAttemptIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test/$attemptId/result': {
      id: '/mock-test/$attemptId/result'
      path: '/mock-test/$attemptId/result'
      fullPath: '/mock-test/$attemptId/result'
      preLoaderRoute: typeof MockTestAttemptIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillTestSlugRoute: SkillTestSlugRoute,
  MockTestIndexRoute: MockTestIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SkillTestIndexRoute: SkillTestIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  MockTestAttemptIdResultRoute: MockTestAttemptIdResultRoute,
  MockTestAttemptIdIndexRoute: MockTestAttemptIdIndexRoute,
  StudyThemeSlugIndexRoute: StudyThemeSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
